steps:
    name: QASE Run tests
    uses: qase-tms/gh-actions/run-complete
    id: complete
    if: always()
    with:
      token: ${{ secrets.QASE_TOKEN }}
      project: CYP
      id: ${{ steps.qase-run-create.outputs.id }}



on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: false
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: false
      qase_project_code: 
        description: 'Project CODE'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Complete Qase Run'
        required: false

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_REPORT: ${{ inputs.qase_report }}
  QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}


jobs:
   
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      env:
        QASE_TESTOPS_API_TOKEN: ${{ env.QASE_API_TOKEN }}
        run: npm test
